# Generated by Django 5.2.8 on 2025-12-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок сайта ')),
                ('descriptions', models.TextField(verbose_name='Описание сайта')),
                ('phone', models.CharField(max_length=100, verbose_name='Номер телефона ')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес сайта ')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Логотип сайта ')),
            ],
            options={
                'verbose_name': 'Название сайт',
                'verbose_name_plural': 'Названии сайта ',
            },
        ),
    ]
